// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLine(arg1) {
  return window['go']['main']['App']['AddLine'](arg1);
}

export function AutoContrast() {
  return window['go']['main']['App']['AutoContrast']();
}

export function ClearLines() {
  return window['go']['main']['App']['ClearLines']();
}

export function ClickCorner(arg1) {
  return window['go']['main']['App']['ClickCorner'](arg1);
}

export function Crop(arg1) {
  return window['go']['main']['App']['Crop'](arg1);
}

export function DetectCorners(arg1) {
  return window['go']['main']['App']['DetectCorners'](arg1);
}

export function DrawDisc(arg1) {
  return window['go']['main']['App']['DrawDisc'](arg1);
}

export function GetCleanPreview() {
  return window['go']['main']['App']['GetCleanPreview']();
}

export function GetLaunchArgs() {
  return window['go']['main']['App']['GetLaunchArgs']();
}

export function GetPixelColor(arg1) {
  return window['go']['main']['App']['GetPixelColor'](arg1);
}

export function GetTouchupSettings() {
  return window['go']['main']['App']['GetTouchupSettings']();
}

export function GetWarpSettings() {
  return window['go']['main']['App']['GetWarpSettings']();
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}

export function OpenSaveDialog() {
  return window['go']['main']['App']['OpenSaveDialog']();
}

export function ProcessLines() {
  return window['go']['main']['App']['ProcessLines']();
}

export function ResetCorners() {
  return window['go']['main']['App']['ResetCorners']();
}

export function ResetDisc() {
  return window['go']['main']['App']['ResetDisc']();
}

export function Rotate(arg1) {
  return window['go']['main']['App']['Rotate'](arg1);
}

export function RotateDisc(arg1) {
  return window['go']['main']['App']['RotateDisc'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SetBackgroundColor(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBackgroundColor'](arg1, arg2, arg3);
}

export function SetCornerDotRadius(arg1) {
  return window['go']['main']['App']['SetCornerDotRadius'](arg1);
}

export function SetFeatherSize(arg1) {
  return window['go']['main']['App']['SetFeatherSize'](arg1);
}

export function SetLevels(arg1) {
  return window['go']['main']['App']['SetLevels'](arg1);
}

export function SetTouchupSettings(arg1) {
  return window['go']['main']['App']['SetTouchupSettings'](arg1);
}

export function SetWarpSettings(arg1) {
  return window['go']['main']['App']['SetWarpSettings'](arg1);
}

export function ShiftDisc(arg1) {
  return window['go']['main']['App']['ShiftDisc'](arg1);
}

export function TouchUpApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['TouchUpApply'](arg1, arg2, arg3);
}

export function TouchUpFill(arg1, arg2, arg3) {
  return window['go']['main']['App']['TouchUpFill'](arg1, arg2, arg3);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}
