// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddLine(arg1:main.LineAddRequest):Promise<main.ProcessResult>;

export function AutoContrast():Promise<main.ProcessResult>;

export function ClearLines():Promise<main.ProcessResult>;

export function ClickCorner(arg1:main.ClickCornerRequest):Promise<main.ClickCornerResult>;

export function Crop(arg1:main.CropRequest):Promise<main.ProcessResult>;

export function DetectCorners(arg1:main.CornerDetectRequest):Promise<main.ProcessResult>;

export function DrawDisc(arg1:main.DiscDrawRequest):Promise<main.ProcessResult>;

export function GetCleanPreview():Promise<main.ProcessResult>;

export function GetDiscSettings():Promise<main.DiscSettings>;

export function GetLaunchArgs():Promise<main.LaunchArgs>;

export function GetPixelColor(arg1:main.PixelColorRequest):Promise<main.ProcessResult>;

export function GetTouchupSettings():Promise<main.TouchupSettings>;

export function GetWarpSettings():Promise<main.WarpSettings>;

export function LoadImage(arg1:main.LoadImageRequest):Promise<main.ImageInfo>;

export function LogFrontend(arg1:string):Promise<void>;

export function OpenImageDialog():Promise<string>;

export function OpenSaveDialog():Promise<string>;

export function ProcessLines():Promise<main.ProcessResult>;

export function ResetCorners():Promise<main.ProcessResult>;

export function ResetDisc():Promise<main.ProcessResult>;

export function RestoreCornerOverlay(arg1:main.RestoreCornerOverlayRequest):Promise<main.ProcessResult>;

export function Rotate(arg1:main.RotateRequest):Promise<main.ProcessResult>;

export function RotateDisc(arg1:main.DiscRotateRequest):Promise<main.ProcessResult>;

export function SaveImage(arg1:main.SaveRequest):Promise<main.ProcessResult>;

export function SetBackgroundColor(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetDiscSettings(arg1:main.DiscSettings):Promise<main.ProcessResult>;

export function SetFeatherSize(arg1:main.FeatherSizeRequest):Promise<main.ProcessResult>;

export function SetLevels(arg1:main.SetLevelsRequest):Promise<main.ProcessResult>;

export function SetTouchupSettings(arg1:main.TouchupSettings):Promise<void>;

export function SetWarpSettings(arg1:main.WarpSettings):Promise<void>;

export function ShiftDisc(arg1:main.ShiftDiscRequest):Promise<main.ProcessResult>;

export function TouchUpApply(arg1:string,arg2:number,arg3:number):Promise<main.ProcessResult>;

export function Undo():Promise<main.ProcessResult>;
