// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLine(arg1) {
  return window['go']['main']['App']['AddLine'](arg1);
}

export function AutoContrast() {
  return window['go']['main']['App']['AutoContrast']();
}

export function CancelTouchup() {
  return window['go']['main']['App']['CancelTouchup']();
}

export function ClearLines() {
  return window['go']['main']['App']['ClearLines']();
}

export function ClickCorner(arg1) {
  return window['go']['main']['App']['ClickCorner'](arg1);
}

export function CompositorLoadResult() {
  return window['go']['main']['App']['CompositorLoadResult']();
}

export function CompositorOpenFilesDialog() {
  return window['go']['main']['App']['CompositorOpenFilesDialog']();
}

export function CompositorOpenSaveDialog() {
  return window['go']['main']['App']['CompositorOpenSaveDialog']();
}

export function CompositorSave(arg1) {
  return window['go']['main']['App']['CompositorSave'](arg1);
}

export function CompositorStitch(arg1) {
  return window['go']['main']['App']['CompositorStitch'](arg1);
}

export function Crop(arg1) {
  return window['go']['main']['App']['Crop'](arg1);
}

export function DetectCorners(arg1) {
  return window['go']['main']['App']['DetectCorners'](arg1);
}

export function DrawDisc(arg1) {
  return window['go']['main']['App']['DrawDisc'](arg1);
}

export function GetCleanPreview() {
  return window['go']['main']['App']['GetCleanPreview']();
}

export function GetAllSettings() {
  return window['go']['main']['App']['GetAllSettings']();
}

export function GetDiscSettings() {
  return window['go']['main']['App']['GetDiscSettings']();
}

export function GetLaunchArgs() {
  return window['go']['main']['App']['GetLaunchArgs']();
}

export function GetPixelColor(arg1) {
  return window['go']['main']['App']['GetPixelColor'](arg1);
}

export function GetTouchupSettings() {
  return window['go']['main']['App']['GetTouchupSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWarpSettings() {
  return window['go']['main']['App']['GetWarpSettings']();
}

export function LoadImage(arg1) {
  return window['go']['main']['App']['LoadImage'](arg1);
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function NormalCrop(arg1) {
  return window['go']['main']['App']['NormalCrop'](arg1);
}

export function OpenImageDialog() {
  return window['go']['main']['App']['OpenImageDialog']();
}

export function OpenSaveDialog() {
  return window['go']['main']['App']['OpenSaveDialog']();
}

export function ProcessLines() {
  return window['go']['main']['App']['ProcessLines']();
}

export function RecropImage() {
  return window['go']['main']['App']['RecropImage']();
}

export function ResetCorners() {
  return window['go']['main']['App']['ResetCorners']();
}

export function ResetDisc() {
  return window['go']['main']['App']['ResetDisc']();
}

export function ResetNormal() {
  return window['go']['main']['App']['ResetNormal']();
}

export function ResizeImage(arg1) {
  return window['go']['main']['App']['ResizeImage'](arg1);
}

export function RestoreCornerOverlay(arg1) {
  return window['go']['main']['App']['RestoreCornerOverlay'](arg1);
}

export function Rotate(arg1) {
  return window['go']['main']['App']['Rotate'](arg1);
}

export function RotateDisc(arg1) {
  return window['go']['main']['App']['RotateDisc'](arg1);
}

export function RunPostSaveCommand(arg1, arg2) {
  return window['go']['main']['App']['RunPostSaveCommand'](arg1, arg2);
}

export function SaveAllSettings(arg1) {
  return window['go']['main']['App']['SaveAllSettings'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SetBackgroundColor(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetBackgroundColor'](arg1, arg2, arg3);
}

export function SetDiscSettings(arg1) {
  return window['go']['main']['App']['SetDiscSettings'](arg1);
}

export function SetFeatherSize(arg1) {
  return window['go']['main']['App']['SetFeatherSize'](arg1);
}

export function SetLevels(arg1) {
  return window['go']['main']['App']['SetLevels'](arg1);
}

export function SetTouchupSettings(arg1) {
  return window['go']['main']['App']['SetTouchupSettings'](arg1);
}

export function SetWarpSettings(arg1) {
  return window['go']['main']['App']['SetWarpSettings'](arg1);
}

export function ShiftDisc(arg1) {
  return window['go']['main']['App']['ShiftDisc'](arg1);
}

export function SkipCrop() {
  return window['go']['main']['App']['SkipCrop']();
}

export function StraightEdgeRotate(arg1) {
  return window['go']['main']['App']['StraightEdgeRotate'](arg1);
}

export function TouchUpApply(arg1, arg2, arg3) {
  return window['go']['main']['App']['TouchUpApply'](arg1, arg2, arg3);
}

export function TrimBorders() {
  return window['go']['main']['App']['TrimBorders']();
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}
